version: '3.7'

services:
  munje:
    image: emwalker/munje
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
    - DATABASE_URL
    - SESSION_KEY
    - SESSION_DOMAIN
    env_file:
    - .env.docker.local
    extra_hosts:
    - "database:172.17.0.1"
    ports:
    - "8080:8080"
