---
apiVersion: v1
kind: Service
metadata:
  name: munje-frontend
spec:
  ports:
  - name: munje-http
    nodePort: 30800
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: munje-https
    nodePort: 30801
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: munje
    tier: frontend
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: munje
    tier: frontend
  name: munje-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: munje
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: munje
        tier: frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: frontend
        envFrom:
        - secretRef:
            name: munje-secrets
        image: emwalker/munje:v23
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 200Mi
      restartPolicy: Always
